---
- name: Install
  hosts: webserver
  become: true
  tasks:
  - name: Install Docker
    yum:
      name: docker
      state: latest
  - name: Restart Docker
    service:
      name: docker
      state: restarted
