---
- name: Install
  hosts: webserver
  become: true
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: removed
    notify: Restart Apache Service
  handlers:
  - name: Restart Apache service
    service:
      name: httpd
      state: install
     


