---
- name: Install
  hosts: webserver
  become: true
  vars:
    pkg_name: "docker"
  tasks:
  - name: Install docker
    yum:
      name: "{{pkg_name}}"
      state: latest
  - name: Restart Docker
    service:
      name: "{{pkg_name}}"
      state: restarted

